import { useSession } from 'next-auth/react'
import Head from 'next/head'
import Image from 'next/image'
import LandingPage from '../components/LandingPage'
import Dashboard from '../components/layout/Dashboard'
import Footer from '../components/layout/Footer'
import Header from '../components/layout/Header'
import styles from '../styles/Home.module.css'

export default function Home() {
  const {data: session } = useSession();

  return (
    <div className='flex flex-col min-h-screen pb-2 bg-theme'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* header */}
      {session && (
        <Header />
      )}

      {/* dashboard */}
      {session ? (
      <Dashboard />
      ):(
        <LandingPage />

      )}

      {/* footer */}
      {/* <Footer /> */}
    </div>
  )
}
